// <auto-generated />
using System;
using Epecps.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Epecps.Infrastructure.Migrations
{
    [DbContext(typeof(EpecpsDbContext))]
    [Migration("20251208062027_AddOverallScoreToReview")]
    partial class AddOverallScoreToReview
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Epecps.Domain.Entities.ApprovalHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ActorRole")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ActorUserId")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("EvaluationId")
                        .HasColumnType("int");

                    b.Property<string>("FromStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("ReviewId")
                        .HasColumnType("int");

                    b.Property<string>("ToStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ActorUserId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("EvaluationId");

                    b.HasIndex("ReviewId");

                    b.ToTable("ApprovalHistories", (string)null);
                });

            modelBuilder.Entity("Epecps.Domain.Entities.AuditLog", b =>
                {
                    b.Property<int>("AuditId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AuditId"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ActorUserId")
                        .HasColumnType("int");

                    b.Property<string>("AfterJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BeforeJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("EntityId")
                        .HasColumnType("int");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("AuditId");

                    b.HasIndex("ActorUserId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("EntityType");

                    b.HasIndex("EntityType", "EntityId");

                    b.ToTable("AuditLogs", (string)null);
                });

            modelBuilder.Entity("Epecps.Domain.Entities.Competency", b =>
                {
                    b.Property<int>("CompetencyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CompetencyId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TargetLevel")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CompetencyId");

                    b.ToTable("Competencies", (string)null);
                });

            modelBuilder.Entity("Epecps.Domain.Entities.Cycle", b =>
                {
                    b.Property<int>("CycleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CycleId"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("CycleId");

                    b.ToTable("Cycles", (string)null);
                });

            modelBuilder.Entity("Epecps.Domain.Entities.Department", b =>
                {
                    b.Property<int>("DeptId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DeptId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("ParentDeptId")
                        .HasColumnType("int");

                    b.HasKey("DeptId");

                    b.HasIndex("ParentDeptId");

                    b.ToTable("Departments", (string)null);
                });

            modelBuilder.Entity("Epecps.Domain.Entities.Document", b =>
                {
                    b.Property<int>("DocumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DocumentId"));

                    b.Property<string>("Checksum")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("EvaluationId")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("Uri")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.HasKey("DocumentId");

                    b.HasIndex("EvaluationId");

                    b.ToTable("Documents", (string)null);
                });

            modelBuilder.Entity("Epecps.Domain.Entities.EmployeeGoal", b =>
                {
                    b.Property<int>("GoalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GoalId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("EvaluationId")
                        .HasColumnType("int");

                    b.Property<string>("EvidenceUri")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("WeightPct")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("GoalId");

                    b.HasIndex("EvaluationId");

                    b.ToTable("EmployeeGoals", (string)null);
                });

            modelBuilder.Entity("Epecps.Domain.Entities.Evaluation", b =>
                {
                    b.Property<int>("EvaluationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EvaluationId"));

                    b.Property<int>("CycleId")
                        .HasColumnType("int");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<Guid?>("GoalSetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("OverallScore")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int?>("PreviousEvaluationId")
                        .HasColumnType("int");

                    b.Property<int>("ReportingManagerId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("TeamLeadId")
                        .HasColumnType("int");

                    b.HasKey("EvaluationId");

                    b.HasIndex("CycleId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("GoalSetId");

                    b.HasIndex("PreviousEvaluationId");

                    b.HasIndex("ReportingManagerId");

                    b.HasIndex("Status");

                    b.HasIndex("TeamLeadId");

                    b.ToTable("Evaluations", (string)null);
                });

            modelBuilder.Entity("Epecps.Domain.Entities.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationId"));

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("NotificationId");

                    b.HasIndex("SentAt");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications", (string)null);
                });

            modelBuilder.Entity("Epecps.Domain.Entities.PeerAssignment", b =>
                {
                    b.Property<int>("PeerAssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PeerAssignmentId"));

                    b.Property<int>("EvaluationId")
                        .HasColumnType("int");

                    b.Property<int>("PeerUserId")
                        .HasColumnType("int");

                    b.HasKey("PeerAssignmentId");

                    b.HasIndex("EvaluationId");

                    b.HasIndex("PeerUserId");

                    b.HasIndex("EvaluationId", "PeerUserId")
                        .IsUnique();

                    b.ToTable("PeerAssignments", (string)null);
                });

            modelBuilder.Entity("Epecps.Domain.Entities.PersonalGoal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<decimal>("CurrentScore")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasDefaultValue(0m);

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("GoalItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("GoalSetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<decimal>("TargetScore")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasDefaultValue(100m);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GoalItemId");

                    b.HasIndex("GoalSetId");

                    b.HasIndex("Status");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "DueDate");

                    b.HasIndex("UserId", "GoalSetId");

                    b.HasIndex("UserId", "Status");

                    b.ToTable("PersonalGoals", (string)null);
                });

            modelBuilder.Entity("Epecps.Domain.Entities.PersonalGoalActivity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EvidenceNotes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("EvidenceUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<bool>("IsFromTemplate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<Guid>("PersonalGoalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<Guid?>("SuggestedActivityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PersonalGoalId");

                    b.HasIndex("Status");

                    b.ToTable("PersonalGoalActivities", (string)null);
                });

            modelBuilder.Entity("Epecps.Domain.Entities.PromotionCase", b =>
                {
                    b.Property<int>("PromotionCaseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PromotionCaseId"));

                    b.Property<string>("DecisionReason")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("EvaluationId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("GmDecidedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("GmDecidedById")
                        .HasColumnType("int");

                    b.Property<int>("GmDecision")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RecommendedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("RecommendedByHodId")
                        .HasColumnType("int");

                    b.HasKey("PromotionCaseId");

                    b.HasIndex("EvaluationId");

                    b.HasIndex("GmDecidedById");

                    b.HasIndex("GmDecision");

                    b.HasIndex("RecommendedByHodId");

                    b.ToTable("PromotionCases", (string)null);
                });

            modelBuilder.Entity("Epecps.Domain.Entities.Review", b =>
                {
                    b.Property<int>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReviewId"));

                    b.Property<int>("EvaluationId")
                        .HasColumnType("int");

                    b.Property<string>("OverallComment")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<decimal?>("OverallScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("ReviewerRole")
                        .HasColumnType("int");

                    b.Property<int>("ReviewerUserId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ReviewId");

                    b.HasIndex("EvaluationId");

                    b.HasIndex("ReviewerUserId");

                    b.HasIndex("Status");

                    b.ToTable("Reviews", (string)null);
                });

            modelBuilder.Entity("Epecps.Domain.Entities.ReviewItem", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ItemId"));

                    b.Property<string>("Comment")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int?>("CompetencyId")
                        .HasColumnType("int");

                    b.Property<int?>("GoalId")
                        .HasColumnType("int");

                    b.Property<decimal>("RatingValue")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("ReviewId")
                        .HasColumnType("int");

                    b.HasKey("ItemId");

                    b.HasIndex("CompetencyId");

                    b.HasIndex("GoalId");

                    b.HasIndex("ReviewId");

                    b.ToTable("ReviewItems", (string)null);
                });

            modelBuilder.Entity("Epecps.Domain.Entities.ReviewScore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("EvaluationId")
                        .HasColumnType("int");

                    b.Property<Guid?>("PersonalGoalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ReviewId")
                        .HasColumnType("int");

                    b.Property<int>("ReviewerId")
                        .HasColumnType("int");

                    b.Property<decimal>("ScoreValue")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EvaluationId");

                    b.HasIndex("PersonalGoalId");

                    b.HasIndex("ReviewId");

                    b.HasIndex("ReviewerId");

                    b.HasIndex("EvaluationId", "ReviewerId");

                    b.ToTable("ReviewScores", (string)null);
                });

            modelBuilder.Entity("Epecps.Domain.Entities.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RoleId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("Epecps.Domain.Entities.ScoreCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<decimal?>("MaxScore")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("ScoreTemplateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("WeightPercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("ScoreTemplateId");

                    b.HasIndex("ScoreTemplateId", "DisplayOrder");

                    b.ToTable("ScoreCategories", (string)null);
                });

            modelBuilder.Entity("Epecps.Domain.Entities.ScoreItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("EvidenceHint")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("EvidenceRequired")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsMandatory")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("ItemType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<decimal>("MaxScore")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("ScoreCategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("TargetScore")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasDefaultValue(100m);

                    b.Property<decimal?>("WeightWithinCategory")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("ScoreCategoryId");

                    b.HasIndex("ScoreCategoryId", "DisplayOrder");

                    b.ToTable("ScoreItems", (string)null);
                });

            modelBuilder.Entity("Epecps.Domain.Entities.ScoreTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsArchived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsPublished")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedByUserId")
                        .HasColumnType("int");

                    b.Property<int>("Version")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.HasIndex("IsArchived");

                    b.HasIndex("IsPublished");

                    b.HasIndex("Name");

                    b.ToTable("ScoreTemplates", (string)null);
                });

            modelBuilder.Entity("Epecps.Domain.Entities.Template", b =>
                {
                    b.Property<int>("TemplateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TemplateId"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("RatingScaleJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("TemplateId");

                    b.ToTable("Templates", (string)null);
                });

            modelBuilder.Entity("Epecps.Domain.Entities.TrainingMaterial", b =>
                {
                    b.Property<int>("TrainingMaterialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TrainingMaterialId"));

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Tags")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("TrainingMaterialId");

                    b.ToTable("TrainingMaterials", (string)null);
                });

            modelBuilder.Entity("Epecps.Domain.Entities.TrainingRecommendation", b =>
                {
                    b.Property<int>("TrainingRecId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TrainingRecId"));

                    b.Property<int>("EvaluationId")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("TrainingMaterialId")
                        .HasColumnType("int");

                    b.HasKey("TrainingRecId");

                    b.HasIndex("EvaluationId");

                    b.HasIndex("TrainingMaterialId");

                    b.ToTable("TrainingRecommendations", (string)null);
                });

            modelBuilder.Entity("Epecps.Domain.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<int>("DeptId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserId");

                    b.HasIndex("DeptId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Epecps.Domain.Entities.UserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", (string)null);
                });

            modelBuilder.Entity("Epecps.Domain.Entities.ApprovalHistory", b =>
                {
                    b.HasOne("Epecps.Domain.Entities.User", "ActorUser")
                        .WithMany()
                        .HasForeignKey("ActorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Epecps.Domain.Entities.Evaluation", "Evaluation")
                        .WithMany()
                        .HasForeignKey("EvaluationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Epecps.Domain.Entities.Review", "Review")
                        .WithMany()
                        .HasForeignKey("ReviewId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ActorUser");

                    b.Navigation("Evaluation");

                    b.Navigation("Review");
                });

            modelBuilder.Entity("Epecps.Domain.Entities.AuditLog", b =>
                {
                    b.HasOne("Epecps.Domain.Entities.User", "ActorUser")
                        .WithMany("AuditLogs")
                        .HasForeignKey("ActorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ActorUser");
                });

            modelBuilder.Entity("Epecps.Domain.Entities.Department", b =>
                {
                    b.HasOne("Epecps.Domain.Entities.Department", "ParentDepartment")
                        .WithMany("SubDepartments")
                        .HasForeignKey("ParentDeptId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentDepartment");
                });

            modelBuilder.Entity("Epecps.Domain.Entities.Document", b =>
                {
                    b.HasOne("Epecps.Domain.Entities.Evaluation", "Evaluation")
                        .WithMany("Documents")
                        .HasForeignKey("EvaluationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Evaluation");
                });

            modelBuilder.Entity("Epecps.Domain.Entities.EmployeeGoal", b =>
                {
                    b.HasOne("Epecps.Domain.Entities.Evaluation", "Evaluation")
                        .WithMany("EmployeeGoals")
                        .HasForeignKey("EvaluationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Evaluation");
                });

            modelBuilder.Entity("Epecps.Domain.Entities.Evaluation", b =>
                {
                    b.HasOne("Epecps.Domain.Entities.Cycle", "Cycle")
                        .WithMany()
                        .HasForeignKey("CycleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Epecps.Domain.Entities.User", "Employee")
                        .WithMany("EvaluationsAsEmployee")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Epecps.Domain.Entities.Evaluation", "PreviousEvaluation")
                        .WithMany("NextEvaluations")
                        .HasForeignKey("PreviousEvaluationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Epecps.Domain.Entities.User", "ReportingManager")
                        .WithMany("EvaluationsAsReportingManager")
                        .HasForeignKey("ReportingManagerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Epecps.Domain.Entities.User", "TeamLead")
                        .WithMany("EvaluationsAsTeamLead")
                        .HasForeignKey("TeamLeadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cycle");

                    b.Navigation("Employee");

                    b.Navigation("PreviousEvaluation");

                    b.Navigation("ReportingManager");

                    b.Navigation("TeamLead");
                });

            modelBuilder.Entity("Epecps.Domain.Entities.Notification", b =>
                {
                    b.HasOne("Epecps.Domain.Entities.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Epecps.Domain.Entities.PeerAssignment", b =>
                {
                    b.HasOne("Epecps.Domain.Entities.Evaluation", "Evaluation")
                        .WithMany("PeerAssignments")
                        .HasForeignKey("EvaluationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Epecps.Domain.Entities.User", "PeerUser")
                        .WithMany("PeerAssignments")
                        .HasForeignKey("PeerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Evaluation");

                    b.Navigation("PeerUser");
                });

            modelBuilder.Entity("Epecps.Domain.Entities.PersonalGoal", b =>
                {
                    b.HasOne("Epecps.Domain.Entities.ScoreItem", "GoalItem")
                        .WithMany("PersonalGoals")
                        .HasForeignKey("GoalItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Epecps.Domain.Entities.User", "User")
                        .WithMany("PersonalGoals")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GoalItem");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Epecps.Domain.Entities.PersonalGoalActivity", b =>
                {
                    b.HasOne("Epecps.Domain.Entities.PersonalGoal", "PersonalGoal")
                        .WithMany("Activities")
                        .HasForeignKey("PersonalGoalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PersonalGoal");
                });

            modelBuilder.Entity("Epecps.Domain.Entities.PromotionCase", b =>
                {
                    b.HasOne("Epecps.Domain.Entities.Evaluation", "Evaluation")
                        .WithMany("PromotionCases")
                        .HasForeignKey("EvaluationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Epecps.Domain.Entities.User", "GmDecidedBy")
                        .WithMany("PromotionCasesDecided")
                        .HasForeignKey("GmDecidedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Epecps.Domain.Entities.User", "RecommendedByHod")
                        .WithMany("PromotionCasesRecommended")
                        .HasForeignKey("RecommendedByHodId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Evaluation");

                    b.Navigation("GmDecidedBy");

                    b.Navigation("RecommendedByHod");
                });

            modelBuilder.Entity("Epecps.Domain.Entities.Review", b =>
                {
                    b.HasOne("Epecps.Domain.Entities.Evaluation", "Evaluation")
                        .WithMany("Reviews")
                        .HasForeignKey("EvaluationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Epecps.Domain.Entities.User", "Reviewer")
                        .WithMany("Reviews")
                        .HasForeignKey("ReviewerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Evaluation");

                    b.Navigation("Reviewer");
                });

            modelBuilder.Entity("Epecps.Domain.Entities.ReviewItem", b =>
                {
                    b.HasOne("Epecps.Domain.Entities.Competency", "Competency")
                        .WithMany("ReviewItems")
                        .HasForeignKey("CompetencyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Epecps.Domain.Entities.EmployeeGoal", "Goal")
                        .WithMany("ReviewItems")
                        .HasForeignKey("GoalId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Epecps.Domain.Entities.Review", "Review")
                        .WithMany("ReviewItems")
                        .HasForeignKey("ReviewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Competency");

                    b.Navigation("Goal");

                    b.Navigation("Review");
                });

            modelBuilder.Entity("Epecps.Domain.Entities.ReviewScore", b =>
                {
                    b.HasOne("Epecps.Domain.Entities.Evaluation", "Evaluation")
                        .WithMany()
                        .HasForeignKey("EvaluationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Epecps.Domain.Entities.PersonalGoal", "PersonalGoal")
                        .WithMany()
                        .HasForeignKey("PersonalGoalId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Epecps.Domain.Entities.Review", "Review")
                        .WithMany("ReviewScores")
                        .HasForeignKey("ReviewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Epecps.Domain.Entities.User", "Reviewer")
                        .WithMany()
                        .HasForeignKey("ReviewerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Evaluation");

                    b.Navigation("PersonalGoal");

                    b.Navigation("Review");

                    b.Navigation("Reviewer");
                });

            modelBuilder.Entity("Epecps.Domain.Entities.ScoreCategory", b =>
                {
                    b.HasOne("Epecps.Domain.Entities.ScoreTemplate", "Template")
                        .WithMany("Categories")
                        .HasForeignKey("ScoreTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Template");
                });

            modelBuilder.Entity("Epecps.Domain.Entities.ScoreItem", b =>
                {
                    b.HasOne("Epecps.Domain.Entities.ScoreCategory", "Category")
                        .WithMany("Items")
                        .HasForeignKey("ScoreCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Epecps.Domain.Entities.TrainingRecommendation", b =>
                {
                    b.HasOne("Epecps.Domain.Entities.Evaluation", "Evaluation")
                        .WithMany("TrainingRecommendations")
                        .HasForeignKey("EvaluationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Epecps.Domain.Entities.TrainingMaterial", "TrainingMaterial")
                        .WithMany("TrainingRecommendations")
                        .HasForeignKey("TrainingMaterialId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Evaluation");

                    b.Navigation("TrainingMaterial");
                });

            modelBuilder.Entity("Epecps.Domain.Entities.User", b =>
                {
                    b.HasOne("Epecps.Domain.Entities.Department", "Department")
                        .WithMany("Users")
                        .HasForeignKey("DeptId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Epecps.Domain.Entities.UserRole", b =>
                {
                    b.HasOne("Epecps.Domain.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Epecps.Domain.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Epecps.Domain.Entities.Competency", b =>
                {
                    b.Navigation("ReviewItems");
                });

            modelBuilder.Entity("Epecps.Domain.Entities.Department", b =>
                {
                    b.Navigation("SubDepartments");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Epecps.Domain.Entities.EmployeeGoal", b =>
                {
                    b.Navigation("ReviewItems");
                });

            modelBuilder.Entity("Epecps.Domain.Entities.Evaluation", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("EmployeeGoals");

                    b.Navigation("NextEvaluations");

                    b.Navigation("PeerAssignments");

                    b.Navigation("PromotionCases");

                    b.Navigation("Reviews");

                    b.Navigation("TrainingRecommendations");
                });

            modelBuilder.Entity("Epecps.Domain.Entities.PersonalGoal", b =>
                {
                    b.Navigation("Activities");
                });

            modelBuilder.Entity("Epecps.Domain.Entities.Review", b =>
                {
                    b.Navigation("ReviewItems");

                    b.Navigation("ReviewScores");
                });

            modelBuilder.Entity("Epecps.Domain.Entities.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Epecps.Domain.Entities.ScoreCategory", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Epecps.Domain.Entities.ScoreItem", b =>
                {
                    b.Navigation("PersonalGoals");
                });

            modelBuilder.Entity("Epecps.Domain.Entities.ScoreTemplate", b =>
                {
                    b.Navigation("Categories");
                });

            modelBuilder.Entity("Epecps.Domain.Entities.TrainingMaterial", b =>
                {
                    b.Navigation("TrainingRecommendations");
                });

            modelBuilder.Entity("Epecps.Domain.Entities.User", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("EvaluationsAsEmployee");

                    b.Navigation("EvaluationsAsReportingManager");

                    b.Navigation("EvaluationsAsTeamLead");

                    b.Navigation("Notifications");

                    b.Navigation("PeerAssignments");

                    b.Navigation("PersonalGoals");

                    b.Navigation("PromotionCasesDecided");

                    b.Navigation("PromotionCasesRecommended");

                    b.Navigation("Reviews");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
