// <auto-generated />
using System;
using Epecps.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Epecps.Infrastructure.Migrations
{
    [DbContext(typeof(EpecpsDbContext))]
    [Migration("20251215_AddReviewScoringModule")]
    partial class AddReviewScoringModule
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            // Note: This is a simplified partial snapshot. The full snapshot would include
            // all existing entities. This is typically auto-generated by EF Core.
            // You should run "dotnet ef migrations add AddReviewScoringModule" to regenerate
            // this file with complete information.
#pragma warning restore 612, 618
        }
    }
}
