#!/usr/bin/env python3
"""Convert a PDF into PNG images.

Primary path: PyMuPDF (fitz), converts all pages.
Fallback path: macOS QuickLook (qlmanage), usually first-page thumbnail.
"""

from __future__ import annotations

import argparse
import shutil
import subprocess
import sys
from pathlib import Path


def convert_with_pymupdf(pdf_path: Path, output_dir: Path, dpi: int) -> list[Path]:
    try:
        import fitz  # type: ignore
    except Exception:
        return []

    images: list[Path] = []
    scale = dpi / 72.0
    matrix = fitz.Matrix(scale, scale)

    with fitz.open(str(pdf_path)) as doc:
        for index, page in enumerate(doc, start=1):
            pixmap = page.get_pixmap(matrix=matrix, alpha=False)
            out_path = output_dir / f"{pdf_path.stem}-page-{index:02d}.png"
            pixmap.save(str(out_path))
            images.append(out_path)

    return images


def convert_with_qlmanage(pdf_path: Path, output_dir: Path, size: int) -> list[Path]:
    qlmanage = shutil.which("qlmanage")
    if not qlmanage:
        raise RuntimeError("qlmanage is not available on this machine.")

    cmd = [qlmanage, "-t", "-s", str(size), "-o", str(output_dir), str(pdf_path)]
    proc = subprocess.run(cmd, capture_output=True, text=True)

    if proc.returncode != 0:
        stderr = proc.stderr.strip() or "Unknown qlmanage error"
        raise RuntimeError(f"qlmanage failed: {stderr}")

    generated = output_dir / f"{pdf_path.name}.png"
    if generated.exists():
        renamed = output_dir / f"{pdf_path.stem}-page-01.png"
        generated.replace(renamed)
        return [renamed]

    fallback = sorted(output_dir.glob(f"{pdf_path.name}*.png"))
    if not fallback:
        raise RuntimeError("No PNG output generated by qlmanage.")

    final_images: list[Path] = []
    for idx, src in enumerate(fallback, start=1):
        dst = output_dir / f"{pdf_path.stem}-page-{idx:02d}.png"
        src.replace(dst)
        final_images.append(dst)

    return final_images


def main() -> int:
    parser = argparse.ArgumentParser(description="Convert a PDF file to PNG images.")
    parser.add_argument("pdf", type=Path, help="Input PDF path")
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=Path("docs/img/pdf-snapshots"),
        help="Directory for output PNG files",
    )
    parser.add_argument(
        "--dpi",
        type=int,
        default=220,
        help="Rendering DPI for PyMuPDF path",
    )
    parser.add_argument(
        "--size",
        type=int,
        default=3200,
        help="QuickLook thumbnail max size for qlmanage fallback",
    )

    args = parser.parse_args()

    pdf_path = args.pdf.expanduser().resolve()
    if not pdf_path.exists() or pdf_path.suffix.lower() != ".pdf":
        print(f"Invalid PDF path: {pdf_path}", file=sys.stderr)
        return 1

    output_dir = args.output_dir.expanduser().resolve()
    output_dir.mkdir(parents=True, exist_ok=True)

    images = convert_with_pymupdf(pdf_path, output_dir, args.dpi)
    method = "PyMuPDF"

    if not images:
        method = "qlmanage"
        images = convert_with_qlmanage(pdf_path, output_dir, args.size)

    print(f"Conversion method: {method}")
    for img in images:
        print(img)

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
